### ISSUE TITLE
Remove default style class from SpeedkitImage & SpeedkitPicture

### ISSUE THREAD

**Issue by woolimi** [GrabarzUndPartner/nuxt-speedkit#665]
**Describe the bug**

I was trying to change nuxt-img component to SpeedkitImage, and then realized that legacy styles are all broken.
That's caused by the own style of SpeedkitImage like below

```css
<style lang="postcss" scoped>
/*! purgecss start ignore */
.nuxt-speedkit-image {
  content-visibility: auto;
  display: block;
  width: 100%;
  height: auto;
  object-fit: cover;
}
/*! purgecss end ignore */
</style>
```

However, I think these classes should be removed and let user decide style. 

**Expected behavior**
